(eval-when-compile    (require 'color-theme))
(defun mwood-cool-blue-color-theme ()
  "Color theme by mwood, created 2015-09-03."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "unspecified-bg")
      (background-mode . light)
      (cursor-color . "#808080")
      (foreground-color . "unspecified-fg"))
     ((compilation-message-face . underline)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (php-default-face . default)
      (php-function-call-face . default)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (bm-fringe-face ((t (:background "#d75f00" :foreground "#1c1c1c"))))
     (bm-fringe-persistent-face ((t (:background "#0087ff" :foreground "#1c1c1c"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (c-nonbreakable-space-face ((t (:background "#d70000"))))
     (change-log-acknowledgement ((t (:italic t :weight normal :slant italic :underline nil :inverse-video nil :foreground "#585858"))))
     (change-log-conditionals ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
     (change-log-date ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
     (change-log-email ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
     (change-log-file ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
     (change-log-function ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
     (change-log-list ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#5f8700"))))
     (change-log-name ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
     (column-marker-1 ((t (:background "#585858"))))
     (column-marker-2 ((t (:background "#00afaf"))))
     (column-marker-3 ((t (:background "#5f5faf"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "#0087ff"))))
     (compilation-column-number ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#af8700"))))
     (compilation-error ((t (:bold t :weight bold :slant normal :underline nil :inverse-video nil :foreground "#d70000"))))
     (compilation-info ((t (:bold t :foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight bold))))
     (compilation-line-number ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#0087ff"))))
     (compilation-warning ((t (:bold t :foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight bold))))
     (completions-annotations ((t (:underline t))))
     (completions-common-part ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :height 1))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "#808080" :foreground "#1c1c1c"))))
     (custom-button ((t (:background "#262626" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:box (:line-width 2 :style released-button) :foreground "#262626" :underline nil :slant normal :weight normal))))
     (custom-button-pressed ((t (:underline nil :foreground "#262626" :box (:line-width 2 :style pressed-button) :underline nil :slant normal :weight normal))))
     (custom-changed ((t (:foreground "#ffffd7" :background "#0087ff" :underline nil :slant normal :weight normal))))
     (custom-comment ((t (:background "#262626"))))
     (custom-comment-tag ((t (:background "#262626"))))
     (custom-documentation ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :height 1))))
     (custom-group-tag ((t (nil))))
     (custom-group-tag-1 ((t (nil))))
     (custom-invalid ((t (:background "#d70000" :underline nil :slant normal :weight normal))))
     (custom-link ((t (:foreground "#5f5faf"))))
     (custom-state ((t (:foreground "#5f8700"))))
     (custom-variable-tag ((t (nil))))
     (diff-added ((t (:foreground "#5f8700"))))
     (diff-changed ((t (:foreground "#af8700"))))
     (diff-file-header ((t (nil))))
     (diff-header ((t (nil))))
     (diff-refine-change ((t (:foreground "#0087ff"))))
     (diff-removed ((t (:foreground "#d70000"))))
     (emacs-wiki-bad-link-face ((t (:foreground "#d70000" :inverse-video nil :underline t :slant normal :weight normal))))
     (emacs-wiki-link-face ((t (:foreground "#0087ff" :inverse-video nil :underline t :slant normal :weight normal))))
     (emacs-wiki-verbatim-face ((t (:foreground "#626262" :inverse-video nil :underline t :slant normal :weight normal))))
     (erc-input-face ((t (:foreground "#585858"))))
     (erc-keyword-face ((t (:bold t :foreground "#af8700" :inverse-video nil :underline nil :weight bold))))
     (erc-my-nick-face ((t (:foreground "#0087ff"))))
     (erc-nick-default-face ((t (:foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight normal))))
     (erc-notice-face ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (erc-timestamp-face ((t (:foreground "#585858"))))
     (error ((t (:bold t :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (escape-glyph-face ((t (:foreground "#d70000"))))
     (eshell-ls-archive ((t (:foreground "#af005f"))))
     (eshell-ls-backup ((t (:foreground "#af8700"))))
     (eshell-ls-clutter ((t (:foreground "#d75f00"))))
     (eshell-ls-directory ((t (:foreground "#0087ff"))))
     (eshell-ls-executable ((t (:foreground "#5f8700"))))
     (eshell-ls-missing ((t (:foreground "#d70000"))))
     (eshell-ls-product ((t (:foreground "#af8700"))))
     (eshell-ls-readonly ((t (nil))))
     (eshell-ls-special ((t (:foreground "#5f5faf"))))
     (eshell-ls-symlink ((t (:foreground "#00afaf"))))
     (eshell-ls-unreadable ((t (:foreground "#626262"))))
     (eshell-prompt ((t (:bold t :foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight bold))))
     (file-name-shadow ((t (:foreground "#585858"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "#d70000" :underline nil :slant normal :weight normal))))
     (flymake-warnline ((t (:bold t :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (flyspell-duplicate ((t (:foreground "#af8700"))))
     (flyspell-incorrect ((t (:foreground "#d70000"))))
     (font-latex-sectioning-5-face ((t (:foreground "#5f5faf"))))
     (font-latex-warning-face ((t (:foreground "#d70000"))))
     (font-lock-builtin-face ((t (:foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-color-constant-face ((t (:foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-comment-delimiter-face ((t (:italic t :foreground "#585858" :inverse-video nil :underline nil :slant italic :weight normal))))
     (font-lock-comment-face ((t (:italic t :foreground "#585858" :inverse-video nil :underline nil :slant italic :weight normal))))
     (font-lock-constant-face ((t (:foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-doc-face ((t (:italic t :foreground "#585858" :inverse-video nil :underline nil :slant italic :weight normal))))
     (font-lock-doc-string-face ((t (:italic t :foreground "#585858" :inverse-video nil :underline nil :slant italic :weight normal))))
     (font-lock-exit-face ((t (:foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-function-name-face ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-keyword-face ((t (:foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-negation-char-face ((t (:foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-other-emphasized-face ((t (:bold t :foreground "#5f5faf" :inverse-video nil :underline nil :weight bold))))
     (font-lock-other-type-face ((t (:italic t :foreground "#0087ff" :inverse-video nil :underline nil :slant italic :weight normal))))
     (font-lock-preprocessor-face ((t (:foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-reference-face ((t (:foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#af8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-regexp-grouping-construct ((t (:foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-special-keyword-face ((t (:foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-string-face ((t (:foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-type-face ((t (:foreground "#af8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-variable-name-face ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (font-lock-warning-face ((t (:bold t :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (fringe ((t (:background "#262626" :foreground "#585858"))))
     (git-gutter:added ((t (:foreground "#5f8700"))))
     (git-gutter:deleted ((t (:foreground "#d70000"))))
     (git-gutter:modified ((t (:foreground "#5f5faf"))))
     (gnus-cite-1 ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-10 ((t (:foreground "#585858" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-11 ((t (:foreground "#262626" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-2 ((t (:foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-3 ((t (:foreground "#af8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-4 ((t (:foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-5 ((t (:foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-6 ((t (:foreground "#5f5faf" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-7 ((t (:foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-8 ((t (:foreground "#af005f" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-cite-9 ((t (:foreground "#626262" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-emphasis-highlight-words ((t (:inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-group-mail-1 ((t (:bold t :foreground "#ffffd7" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "#ffffd7"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "#e4e4e4" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "#e4e4e4"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "#af005f" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "#af005f"))))
     (gnus-group-mail-low ((t (:bold t :foreground "#626262" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "#626262"))))
     (gnus-group-news-1 ((t (:bold t :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-group-news-1-empty ((t (nil))))
     (gnus-group-news-2 ((t (:bold t :foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "#0087ff"))))
     (gnus-group-news-low ((t (:bold t :foreground "#5f5faf" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "#5f5faf"))))
     (gnus-header-content ((t (:foreground "#585858" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-header-from ((t (:foreground "#626262" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-header-name ((t (:foreground "#585858" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-header-newsgroups ((t (:foreground "#262626" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-header-subject ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-server-agent ((t (:bold t :foreground "#ffffd7" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-server-closed ((t (:italic t :inverse-video nil :underline nil :slant italic :weight normal))))
     (gnus-server-denied ((t (:bold t :foreground "#e4e4e4" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-server-offline ((t (:bold t :foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-server-opened ((t (:bold t :foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-signature ((t (:foreground "#585858" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-splash ((t (:foreground "#e4e4e4"))))
     (gnus-summary-cancelled ((t (:foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-summary-high-ancient ((t (:bold t :underline nil :inverse-video nil :foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-summary-high-read ((t (:bold t :underline nil :inverse-video nil :foreground "#585858" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :underline nil :inverse-video nil :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :underline nil :inverse-video nil :foreground "#e4e4e4" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :underline nil :inverse-video nil :foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :underline nil :inverse-video nil :foreground "#0087ff" :inverse-video nil :underline nil :slant italic :weight normal))))
     (gnus-summary-low-read ((t (:italic t :underline nil :inverse-video nil :foreground "#0087ff" :inverse-video nil :underline nil :slant italic :weight normal))))
     (gnus-summary-low-ticked ((t (:italic t :underline nil :inverse-video nil :foreground "#0087ff" :inverse-video nil :underline nil :slant italic :weight normal))))
     (gnus-summary-low-undownloaded ((t (:italic t :underline nil :inverse-video nil :foreground "#0087ff" :inverse-video nil :underline nil :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :underline nil :inverse-video nil :foreground "#0087ff" :inverse-video nil :underline nil :slant italic :weight normal))))
     (gnus-summary-normal-ancient ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-summary-normal-read ((t (:foreground "#585858" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-summary-normal-ticked ((t (:foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-summary-normal-undownloaded ((t (:foreground "#e4e4e4" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-summary-normal-unread ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (gnus-summary-selected ((t (:background "#af8700" :foreground "#1c1c1c" :inverse-video nil :underline nil :slant normal :weight normal))))
     (header-line ((t (:foreground "#262626" :underline nil :slant normal :weight normal))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:background "#262626"))))
     (hl-line ((t (:background "#262626" :underline nil))))
     (ido-first-match ((t (:bold t :foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight bold))))
     (ido-only-match ((t (:foreground "#5f8700"))))
     (ido-subdir ((t (:foreground "#0087ff"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "brown"))))
     (info-header-xref ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#0087ff"))))
     (info-menu-header ((t (:bold t :underline t :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "green" :weight bold))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold))))
     (info-title-3 ((t (:bold t :weight bold))))
     (info-title-4 ((t (:bold t :weight bold))))
     (info-xref ((t (:foreground "#0087ff" :inverse-video nil :underline t :slant normal :weight normal))))
     (info-xref-visited ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#af005f"))))
     (isearch ((t (:background "#d75f00" :underline nil :slant normal :weight normal))))
     (isearch-fail ((t (:background "#d75f00" :underline nil :slant normal :weight normal))))
     (italic ((t (:underline t))))
     (jabber-activity-face ((t (:bold t :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (jabber-activity-personal-face ((t (:bold t :foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight bold))))
     (jabber-chat-error ((t (:bold t :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (jabber-chat-prompt-foreign ((t (:bold t :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (jabber-chat-prompt-local ((t (:bold t :foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight bold))))
     (jabber-chat-prompt-system ((t (:bold t :foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight bold))))
     (jabber-chat-rare-time-face ((t (:foreground "#5f8700" :inverse-video nil :underline t :slant normal :weight normal))))
     (jabber-chat-text-foreign ((t (nil))))
     (jabber-chat-text-local ((t (nil))))
     (jabber-roster-user-away ((t (:italic t :foreground "#5f8700" :inverse-video nil :underline nil :slant italic :weight normal))))
     (jabber-roster-user-chatty ((t (:bold t :foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight bold))))
     (jabber-roster-user-dnd ((t (:italic t :foreground "#d70000" :inverse-video nil :underline nil :slant italic :weight normal))))
     (jabber-roster-user-error ((t (:italic t :foreground "#d70000" :slant italic :weight light))))
     (jabber-roster-user-offline ((t (:foreground "#585858"))))
     (jabber-roster-user-online ((t (:bold t :foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight bold))))
     (jabber-roster-user-xa ((t (:italic t :foreground "#af005f" :inverse-video nil :underline nil :slant italic :weight normal))))
     (lazy-highlight ((t (:background "#af8700" :underline nil :slant normal :weight normal))))
     (link ((t (:foreground "#5f5faf" :inverse-video nil :underline t :slant normal :weight normal))))
     (link-visited ((t (:foreground "#af005f" :inverse-video nil :underline t :slant normal :weight normal))))
     (linum ((t (:background "#262626" :foreground "#585858"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (:background "#262626"))))
     (message-cited-text ((t (:foreground "#e4e4e4"))))
     (message-header-cc ((t (:bold t :foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight bold))))
     (message-header-name ((t (:foreground "#00afaf"))))
     (message-header-newsgroups ((t (:bold t :foreground "#af8700" :inverse-video nil :underline nil :weight bold))))
     (message-header-other ((t (:foreground "#d70000"))))
     (message-header-subject ((t (:foreground "#626262"))))
     (message-header-to ((t (:bold t :inverse-video nil :underline nil :slant normal :weight bold))))
     (message-header-xheader ((t (:foreground "#5f5faf"))))
     (message-mml ((t (:foreground "#0087ff"))))
     (message-separator ((t (:foreground "#ffffd7"))))
     (minibuffer-prompt ((t (:bold t :foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight bold))))
     (mode-line ((t (:foreground "#262626" :box nil :underline nil :slant normal :weight normal))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:foreground "#262626" :background "#626262" :box nil :underline nil :slant normal :weight normal))))
     (mouse ((t (nil))))
     (next-error ((t (:weight normal :slant normal :underline nil :background "#585858" :foreground "#1c1c1c"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (org-cancelled-kwd-face ((t (:background "#1c1c1c" :foreground "#5f8700"))))
     (org-delegated-kwd-face ((t (:background "#1c1c1c" :foreground "#00afaf"))))
     (org-done ((t (:bold t :foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight bold))))
     (org-done-kwd-face ((t (:background "#1c1c1c" :foreground "#5f8700"))))
     (org-hide ((t (:foreground "#1c1c1c"))))
     (org-project-kwd-face ((t (:background "#1c1c1c" :foreground "#5f5faf"))))
     (org-someday-kwd-face ((t (:background "#1c1c1c" :foreground "#0087ff"))))
     (org-started-kwd-face ((t (:background "#1c1c1c" :foreground "#af8700"))))
     (org-todo ((t (:bold t :background "#d70000" :foreground "#1c1c1c" :inverse-video nil :underline nil :slant normal :weight bold))))
     (org-todo-kwd-face ((t (:background "#1c1c1c" :foreground "#d70000"))))
     (org-waiting-kwd-face ((t (:background "#1c1c1c" :foreground "#d75f00"))))
     (outline-1 ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (outline-2 ((t (:foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight normal))))
     (outline-3 ((t (:foreground "#af8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (outline-4 ((t (:foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight normal))))
     (outline-5 ((t (:inverse-video nil :underline nil :slant normal :weight normal))))
     (outline-6 ((t (:foreground "#585858" :inverse-video nil :underline nil :slant normal :weight normal))))
     (outline-7 ((t (:foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight normal))))
     (outline-8 ((t (:foreground "#5f5faf" :inverse-video nil :underline nil :slant normal :weight normal))))
     (paren-face ((t (:foreground "#585858"))))
     (php-annotations-annotation-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#00afaf"))))
     (pp^L-highlight ((t (nil))))
     (query-replace ((t (:weight normal :slant normal :underline nil :background "#d75f00"))))
     (rainbow-delimiters-depth-1-face ((t (:foreground "#00afaf"))))
     (rainbow-delimiters-depth-2-face ((t (:foreground "#af8700"))))
     (rainbow-delimiters-depth-3-face ((t (:foreground "#0087ff"))))
     (rainbow-delimiters-depth-4-face ((t (:foreground "#d70000"))))
     (rainbow-delimiters-depth-5-face ((t (:foreground "#5f8700"))))
     (rainbow-delimiters-depth-6-face ((t (:foreground "#0087ff"))))
     (rainbow-delimiters-depth-7-face ((t (:foreground "#d75f00"))))
     (rainbow-delimiters-depth-8-face ((t (:foreground "#af005f"))))
     (rainbow-delimiters-depth-9-face ((t (nil))))
     (rcirc-bright-nick ((t (:foreground "#af005f"))))
     (rcirc-my-nick ((t (:foreground "#0087ff"))))
     (rcirc-nick-in-message ((t (:foreground "#d75f00"))))
     (rcirc-other-nick ((t (:foreground "#5f8700"))))
     (rcirc-prompt ((t (:foreground "#af8700"))))
     (rcirc-server ((t (:foreground "#8a8a8a"))))
     (rcirc-timestamp ((t (:foreground "#585858"))))
     (region ((t (:foreground "#1c1c1c" :background "#585858" :underline nil :slant normal :weight normal))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "#262626"))))
     (shadow ((t (:foreground "#585858"))))
     (show-paren-match ((t (:bold t :background "#262626" :foreground "#00afaf" :inverse-video nil :underline nil :slant normal :weight bold))))
     (show-paren-mismatch ((t (:bold t :background "#585858" :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (slime-error-face ((t (:background "#d70000" :underline nil :slant normal :weight normal))))
     (slime-note-face ((t (:foreground "#af8700"))))
     (slime-repl-inputted-output-face ((t (:foreground "#d70000"))))
     (slime-repl-output-mouseover-face ((t (:box (:color "#ffffd7")))))
     (slime-style-warning-face ((t (:bold t :foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight bold))))
     (slime-warning-face ((t (:bold t :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (speedbar-button-face ((t (:inverse-video nil :underline nil :slant normal :weight normal))))
     (speedbar-directory-face ((t (:foreground "#d75f00" :inverse-video nil :underline nil :slant normal :weight normal))))
     (speedbar-file-face ((t (:foreground "#5f8700" :inverse-video nil :underline nil :slant normal :weight normal))))
     (speedbar-highlight-face ((t (:background "#262626"))))
     (speedbar-selected-face ((t (:foreground "#af8700" :inverse-video nil :underline t :slant normal :weight normal))))
     (speedbar-separator-face ((t (:underline nil :slant normal :weight normal))))
     (speedbar-tag-face ((t (:foreground "#0087ff" :inverse-video nil :underline nil :slant normal :weight normal))))
     (table-cell ((t (:inverse-video nil :underline nil :slant normal :weight normal))))
     (term-color-black ((t (:foreground "#262626"))))
     (term-color-blue ((t (:foreground "#0087ff"))))
     (term-color-cyan ((t (:foreground "#00afaf"))))
     (term-color-green ((t (:foreground "#5f8700"))))
     (term-color-magenta ((t (:foreground "#af005f"))))
     (term-color-red ((t (:foreground "#d70000"))))
     (term-color-white ((t (:foreground "#626262"))))
     (term-color-yellow ((t (:foreground "#af8700"))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "#d70000" :underline nil :slant normal :weight normal))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (whitespace-empty ((t (:foreground "#d70000"))))
     (whitespace-highlight-face ((t (:background "#0087ff" :foreground "#d70000"))))
     (whitespace-hspace ((t (:foreground "#d75f00"))))
     (whitespace-indentation ((t (:foreground "#262626"))))
     (whitespace-line ((t (:background "#1c1c1c" :foreground "#af005f"))))
     (whitespace-space ((t (:foreground "#262626"))))
     (whitespace-space-after-tab ((t (:foreground "#00afaf"))))
     (whitespace-space-before-tab ((t (:bold t :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (whitespace-tab ((t (:foreground "#262626"))))
     (whitespace-trailing ((t (:bold t :background "#262626" :foreground "#d70000" :inverse-video nil :underline nil :slant normal :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :inverse-video nil :foreground "unspecified-fg" :stipple nil :background "#262626" :box (:line-width 1) :height 1))))
     (widget-inactive ((t (:foreground "#585858"))))
     (widget-single-line-field ((t (:box (:line-width 1) :background "#262626" :stipple nil :foreground "unspecified-fg" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :height 1)))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))